// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhpvoqJEDwRrmH2bTd9dWvdyl89mgm3pw',
    appId: '1:1021339625916:web:eb3a562d3e2f5643fca3b9',
    messagingSenderId: '1021339625916',
    projectId: 'scanner-a64d2',
    authDomain: 'scanner-a64d2.firebaseapp.com',
    storageBucket: 'scanner-a64d2.appspot.com',
    measurementId: 'G-D1EDHGS814',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3-8elKSoaoxVNGx793hWCm1BlFI6egkw',
    appId: '1:1021339625916:android:dced9c934d36b096fca3b9',
    messagingSenderId: '1021339625916',
    projectId: 'scanner-a64d2',
    storageBucket: 'scanner-a64d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYZVunWRvhMdaKjZZ--A2ES5lbYb44lRU',
    appId: '1:1021339625916:ios:107445e592c5a8f3fca3b9',
    messagingSenderId: '1021339625916',
    projectId: 'scanner-a64d2',
    storageBucket: 'scanner-a64d2.appspot.com',
    iosClientId: '1021339625916-oc8s1pu91daaa3s7uqoc8vo0va75i3u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.scanner',
  );
}
